"""claude-usage-autoresume — scheduling half.

Turns a resolved reset time into a durable `hermes cron` one-shot job that
resumes the halted session with `hermes chat --resume <session_id>`.

Implementation choice: shell out to the `hermes cron create` CLI rather than
import `cron/jobs.py` internals directly. The CLI is the stable, documented
surface (`hermes cron create --help`); cron's internal function names are
not something a `~/.hermes/plugins/` package should depend on across Hermes
upgrades. The job itself runs in `--no-agent` "script IS the job" mode
(see `hermes cron create --help`) so firing it costs no extra LLM call of
its own — it just shells `hermes chat --resume ...` and lets that resumed
session's own turn continue where it left off.
"""

from __future__ import annotations

import logging
import subprocess
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

logger = logging.getLogger("plugin.claude_usage_autoresume")

# Buffer past the provider's own reset instant, mirroring the pattern in
# Hermes's own cron/quota_hold.py (HOLD_SLACK_SECONDS) — avoid firing one
# tick before the window has actually reopened.
RESUME_BUFFER_SECONDS = 60

def _scripts_dir() -> Path:
    """``$HERMES_HOME/scripts`` — NOT ``Path.home()/.hermes``: those differ on
    this Windows install (real home resolves under AppData\\Local\\hermes)."""
    try:
        from hermes_constants import get_hermes_home
        return get_hermes_home() / "scripts"
    except Exception:
        return Path.home() / ".hermes" / "scripts"


_SCRIPTS_DIR = _scripts_dir()

_RESUME_SCRIPT_TEMPLATE = '''"""Auto-generated by claude-usage-autoresume. Safe to delete after it runs
once (--no-agent cron jobs are one-shot; nothing re-reads this file)."""
import subprocess
import sys

SESSION_ID = {session_id!r}

def main() -> int:
    proc = subprocess.run(
        ["hermes", "chat", "-q", "Continue where we left off.", "--oneshot",
         "--resume", SESSION_ID, "-Q"],
        capture_output=True, text=True,
    )
    sys.stdout.write(proc.stdout)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        sys.stdout.write(
            f"\\n[claude-usage-autoresume] resume of session {{SESSION_ID}} "
            f"exited {{proc.returncode}} — resume it manually with: "
            f"hermes --resume {{SESSION_ID}}\\n"
        )
    return 0  # never fail the cron run itself; the message above is enough

if __name__ == "__main__":
    raise SystemExit(main())
'''


def _safe_slug(session_id: str) -> str:
    return "".join(c for c in session_id if c.isalnum() or c in "-_") or "session"


def _write_resume_script(session_id: str) -> Path:
    _SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
    script_path = _SCRIPTS_DIR / f"autoresume_{_safe_slug(session_id)}.py"
    script_path.write_text(_RESUME_SCRIPT_TEMPLATE.format(session_id=session_id), encoding="utf-8")
    return script_path


def schedule_resume_job(*, session_id: str, resume_at: datetime) -> Optional[str]:
    """Queue the one-shot resume job. Returns the new job's id/name Hermes
    reports on stdout, or None if scheduling failed (logged, never raised —
    the caller is a fail-open plugin hook)."""
    fire_at = (resume_at + timedelta(seconds=RESUME_BUFFER_SECONDS)).isoformat()
    script_path = _write_resume_script(session_id)
    job_name = f"claude-usage-autoresume-{_safe_slug(session_id)[:16]}"
    cmd = [
        "hermes", "cron", "create", fire_at,
        "--name", job_name,
        "--script", script_path.name,
        "--no-agent",
        "--deliver", "local",
        "--repeat", "1",
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    except Exception:
        logger.exception("claude-usage-autoresume: `hermes cron create` failed to run")
        return None
    if result.returncode != 0:
        logger.error("claude-usage-autoresume: `hermes cron create` exited %s: %s",
                      result.returncode, result.stderr.strip())
        return None
    logger.debug("claude-usage-autoresume: cron create output: %s", result.stdout.strip())
    return result.stdout.strip() or job_name
