"""hermes-autoretry-limit — scheduling half.

Turns a resolved reset time into a durable `hermes cron` one-shot job that
resumes the halted session with `hermes chat --resume <session_id>`.

Implementation choice: shell out to the `hermes cron create` CLI rather than
import `cron/jobs.py` internals directly. The CLI is the stable, documented
surface (`hermes cron create --help`); cron's internal function names are
not something a `~/.hermes/plugins/` package should depend on across Hermes
upgrades. The job itself runs in `--no-agent` "script IS the job" mode
(see `hermes cron create --help`) so firing it costs no extra LLM call of
its own — it just shells `hermes chat --resume ...` and lets that resumed
session's own turn continue where it left off.
"""

from __future__ import annotations

import logging
import subprocess
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

logger = logging.getLogger("plugin.claude_usage_autoresume")

# Buffer past the provider's own reset instant, mirroring the pattern in
# Hermes's own cron/quota_hold.py (HOLD_SLACK_SECONDS) — avoid firing one
# tick before the window has actually reopened.
RESUME_BUFFER_SECONDS = 60
# When a fired resume finds the window STILL closed (unknown/underestimated reset,
# provider re-cap), it re-schedules its own re-check this many minutes out instead of
# resuming. Kept ~55 min so the whole script run always finishes well inside Hermes's
# one-hour cron script timeout (cron.script_timeout_seconds), which kills the script's
# ENTIRE process tree on expiry — an in-progress `hermes chat --resume` included.
HOP_MINUTES = 55

def _scripts_dir() -> Path:
    """``$HERMES_HOME/scripts`` — NOT ``Path.home()/.hermes``: those differ on
    this Windows install (real home resolves under AppData\\Local\\hermes)."""
    try:
        from hermes_constants import get_hermes_home
        return get_hermes_home() / "scripts"
    except Exception:
        return Path.home() / ".hermes" / "scripts"


_SCRIPTS_DIR = _scripts_dir()

_RESUME_SCRIPT_TEMPLATE = '''"""Auto-generated by hermes-autoretry-limit. NOT safe to delete while a
usage window is still closed: each run re-schedules its own next check.

Fired as a one-shot `hermes cron --no-agent` job. At fire time:
- usage windows for this session's provider are fetched via the plugin's limits module;
- window open   -> run `hermes chat --resume` synchronously and exit (the resumed
  session re-arms this whole chain itself if it hits the limit again);
- closed/unknown-> create the NEXT one-shot check ~{hop_minutes} minutes out and exit.
Every run therefore lasts seconds, far inside Hermes's one-hour cron script kill.
"""
import importlib.util
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

SESSION_ID = {session_id!r}
PROVIDER = {provider!r}
HOP_MINUTES = {hop_minutes}
SCRIPT_PATH = Path(__file__).resolve()


def _load_plugin():
    """Import the installed plugin package (Hermes loads it as hermes_plugins.<slug>;
    fall back to a direct load from its directory for robustness)."""
    for name in tuple(sys.modules):
        if name.startswith("hermes_plugins."):
            mod = sys.modules[name]
            if getattr(mod, "limits", None) is not None and getattr(mod, "schedule", None) is not None:
                return mod
    plugin_dir = {plugin_dir!r}
    spec = importlib.util.spec_from_file_location(
        "_autoresume_plugin", Path(plugin_dir) / "__init__.py",
        submodule_search_locations=[plugin_dir])
    mod = importlib.util.module_from_spec(spec)
    sys.modules["_autoresume_plugin"] = mod
    spec.loader.exec_module(mod)
    return mod


def _windows_open(plugin) -> bool:
    try:
        windows = plugin.limits.fetch_windows_cached(PROVIDER)
        epoch = plugin.limits.blocking_reset_epoch(windows, now=datetime.now(timezone.utc).timestamp())
        return epoch is None
    except Exception:
        return True  # usage API unreachable: try to resume rather than stall the chain


def _schedule_next_hop() -> None:
    fire_at = datetime.now(timezone.utc) + timedelta(minutes=HOP_MINUTES)
    name = f"autoresume-{{_safe_slug(SESSION_ID)}}-{{int(fire_at.timestamp())}}"
    cmd = ["hermes", "cron", "create", fire_at.isoformat(),
           "--name", name, "--script", SCRIPT_PATH.name, "--no-agent",
           "--deliver", "local", "--failure-deliver", "local", "--repeat", "1"]
    if sys.executable:
        cmd += ["--interpreter", sys.executable]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    if proc.returncode != 0:
        sys.stderr.write(f"[hermes-autoretry-limit] next-hop scheduling FAILED ({{proc.returncode}}): "
                         f"{{proc.stderr.strip()}} — resume manually with: hermes --resume {{SESSION_ID}}\\n")
    else:
        sys.stdout.write(f"[hermes-autoretry-limit] {{PROVIDER}} window still closed — next check {{fire_at.isoformat(timespec='minutes')}} (job {{name}})\\n")


def main() -> int:
    if not _windows_open(_load_plugin()):
        _schedule_next_hop()
        return 0
    proc = subprocess.run(
        ["hermes", "chat", "-q", "Continue where we left off.", "--oneshot",
         "--resume", SESSION_ID, "-Q"],
        capture_output=True, text=True,
    )
    sys.stdout.write(proc.stdout)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        sys.stdout.write(
            f"\\n[hermes-autoretry-limit] resume of session {{SESSION_ID}} "
            f"exited {{proc.returncode}} — resume it manually with: "
            f"hermes --resume {{SESSION_ID}}\\n"
        )
    return 0  # never fail the cron run itself; the messages above are enough

if __name__ == "__main__":
    raise SystemExit(main())
'''


def _safe_slug(session_id: str) -> str:
    return "".join(c for c in session_id if c.isalnum() or c in "-_") or "session"


def _write_resume_script(session_id: str, provider: str = "anthropic") -> Path:
    _SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
    script_path = _SCRIPTS_DIR / f"autoresume_{_safe_slug(session_id)}.py"
    try:
        plugin_dir = str(Path(__file__).resolve().parent)
    except Exception:
        plugin_dir = ""
    script_path.write_text(_RESUME_SCRIPT_TEMPLATE.format(
        session_id=session_id, provider=provider, plugin_dir=plugin_dir,
        hop_minutes=HOP_MINUTES), encoding="utf-8")
    return script_path


def build_cron_command(*, session_id: str, resume_at: datetime, script_name: str,
                       interpreter: Optional[str] = None) -> list:
    """The exact `hermes cron create` argv for one resume. Job name carries the
    fire time so every link of the resume chain is distinct in `hermes cron list`."""
    fire_at = resume_at + timedelta(seconds=RESUME_BUFFER_SECONDS)
    job_name = f"hermes-autoretry-limit-{_safe_slug(session_id)[:16]}-{int(fire_at.timestamp())}"
    cmd = [
        "hermes", "cron", "create", fire_at.isoformat(),
        "--name", job_name,
        "--script", script_name,
        "--no-agent",
        "--deliver", "local",
        "--failure-deliver", "local",
        "--repeat", "1",
    ]
    if interpreter:
        cmd += ["--interpreter", interpreter]
    return cmd


def schedule_resume_job(*, session_id: str, resume_at: datetime,
                        provider: str = "anthropic") -> Optional[str]:
    """Queue the one-shot resume job. Returns the new job's id/name Hermes
    reports on stdout, or None if scheduling failed (logged, never raised —
    the caller is a fail-open plugin hook)."""
    script_path = _write_resume_script(session_id, provider)
    cmd = build_cron_command(session_id=session_id, resume_at=resume_at,
                             script_name=script_path.name, interpreter=sys.executable or None)
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    except Exception:
        logger.exception("hermes-autoretry-limit: `hermes cron create` failed to run")
        return None
    if result.returncode != 0:
        logger.error("hermes-autoretry-limit: `hermes cron create` exited %s: %s",
                      result.returncode, result.stderr.strip())
        return None
    logger.debug("hermes-autoretry-limit: cron create output: %s", result.stdout.strip())
    return result.stdout.strip() or cmd[cmd.index("--name") + 1]
